title: Site

tabs:
  main:
    label: Main
    icon: text
    columns:
      main_1:
        width: 1/2
        sections:
          # The `pages` pages section shows other main pages of the site
          # Using the `templates` option, we limit which types of pages are shown
          # Using the `create` option, we limit the type of page that can be created when a new page is created
          # Note that the `sandbox` page and the `error` page that also exist in the content folder but use different blueprints thus do not show up in the list
          # Since the error page's blueprint is set to `read: false`, it wouldn't show up here even if you added the error blueprint to the templates list
          seniors:
            headline: Seniors
            type: fields
            fields:
              senior_title:
                type: text
                label: Senior Title
              senior_subtitle:
                type: text
                label: Senior Subtitle
          senior_list:
            type: pages
            headline: Seniors
            templates:
              - senior
                # fields:
                #   name:
                #     type: text
                #     label: Name
                #   show_title:
                #     type: text
                #     label: Show Title
                #   hero_image:
                #     type: files
                #     max: 1
                #     label: Hero Image
                #   content_type:
                #     type: select
                #     options: 
                #        - Gallery
                #        - Link
                #        - Embed
                #     default: Gallery
                #     required: true
                #     label: Content Type
                #   gallery:
                #     type: files
                #     label: Gallery
                #     when:
                #       content_type: Gallery
                #   link:
                #     type: text
                #     label: Link
                #     when:
                #       content_type: Link
                #   Embed:
                #     type: text
                #     label: Embed Code
                #     when:
                #       content_type: Embed
      main_2:
        width: 1/2
        sections:
          juniors:
            headline: Juniors
            type: fields
            fields:
              junior_title:
                type: text
                label: Junior Title
              junior_subtitle:
                type: text
                label: Junior Subtitle
          junior_list:
            headline: Juniors
            type: pages
            templates:
              - junior
          # info:
          #   type: info
          #   headline: Formatting
          #   text: |
          #     For more information on formatting, visit [this Kirby guide](https://getkirby.com/docs/guide/content/text-formatting)
          #     or [this Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
  settings:
    label: Settings
    icon: cog
    columns:
      settings_1:
        width: 1/2
        fields:
          ga:
            label: Google Analytics Code
            type: text
          meta_description:
            label: Site Meta Description
            type: text
      settings_2:
        width: 1/2
        sections:
          main_info:
            type: fields
            fields:
              about:
                label: About
                type: textarea
                size: medium
          other:
            headline: Error
            type: pages
            templates:
              - error